---
title: "CodeBook: Analyzing Wearable Computing Data"
author: "Coursera | Getting and Cleaning Data Course Project"
date: "Clara Abdurazak | January 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

-----

## About this Code Book

This code book describes the variables, data (including units), transformations and calculations performed to clean up and summarize the Samsung wearable computing data. 

### Data to be Analyzed:

**IMPORTANT:** The `run_analysis.R` script will run correctly as long as the Samsung data is in your working directory within a folder named `\data`. 

**At a minimum, please ensure that the following Samsung data files are in your `\data` folder before running the script:**

- `\test` - a folder containing the files: `subject_test.txt`, `X_test.txt`, `Y_test.txt`

- `\train` - a folder containing the files: `subject_train.txt`, `X_train.txt`, `Y_train.txt`

- `features.txt`

*(The other files contained in the Samsung data set are not necessary for this analysis.)*

-----

# Data, Calculations and Variables

### Description of Raw (Samsung) Data

The raw data to be analyzed by this program was collected from the accelerometers from the Samsung Galaxy S smartphone. A full description of the Samsung data (including download links) is available here: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones


### Description of Calculations and Transformations Performed

blah


### Description of Variables

*(NOTE: A complete description of the variables from the raw data set (and information on how specific measurements were obtained) can be found in the `features_info.txt` file included in the Samsung data set.)*

Description of variables in the `tidy_data.txt` file generated by the `run_analysis.R` script:


- **`Subject`** : `[integer]` : Identifies the subject who performed the activity for each sample. Its range is from 1 to 30.

- **`Activity`** : `[factor]` :  Identifies activities performed. Possible values are: `Laying`, `Sitting`, `Standing`, `Walking`, `WalkingDownstairs`, and `WalkingUpstairs`  

- **`timeBodyAccMeanX`** : `[double]` : Indicates average of the MEAN of time domain signals for body movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`timeBodyAccMeanY`** : `[double]` : Indicates average of the MEAN of time domain signals for body movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyAccMeanZ`** : `[double]` : Indicates average of the MEAN of time domain signals for body movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyAccStdX`** : `[double]` : Indicates average of the STD of time domain signals for body movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`timeBodyAccStdY`** : `[double]` : Indicates average of the STD of time domain signals for body movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyAccStdZ`** : `[double]` : Indicates average of the STD of time domain signals for body movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`timeGravityAccMeanX`** : `[double]` : Indicates average of the MEAN of time domain signals for gravity movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`timeGravityAccMeanY`** : `[double]` : Indicates average of the MEAN of time domain signals for gravity movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`timeGravityAccMeanZ`** : `[double]` : Indicates average of the MEAN of time domain signals for gravity movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`timeGravityAccStdX`** : `[double]` : Indicates average of the STD of time domain signals for gravity movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`timeGravityAccStdY`** : `[double]` : Indicates average of the STD of time domain signals for gravity movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`timeGravityAccStdZ`** : `[double]` : Indicates average of the STD of time domain signals for gravity movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyAccJerkMeanX`** : `[double]` : Indicates average of the MEAN of time domain signals for body 'Jerk' movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`timeBodyAccJerkMeanY`** : `[double]` : Indicates average of the MEAN of time domain signals for body 'Jerk' movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyAccJerkMeanZ`** : `[double]` : Indicates average of the MEAN of time domain signals for body 'Jerk' movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyAccJerkStdX`** : `[double]` : Indicates average of the STD of time domain signals for body 'Jerk' movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`timeBodyAccJerkStdY`** : `[double]` : Indicates average of the STD of time domain signals for body 'Jerk' movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyAccJerkStdZ`** : `[double]` : Indicates average of the STD of time domain signals for body 'Jerk' movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyGyroMeanX`** : `[double]` : Indicates average of the MEAN of time domain signals for body movement captured by gyroscope on the X axis, denoted in units hertz (Hz).  

- **`timeBodyGyroMeanY`** : `[double]` : Indicates average of the MEAN of time domain signals for body movement captured by gyroscope on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyGyroMeanZ`** : `[double]` : Indicates average of the MEAN of time domain signals for body movement captured by gyroscope on the Z axis, denoted in units hertz (Hz).  
- **`timeBodyGyroStdX`** : `[double]` : Indicates average of the STD of time domain signals for body movement captured by gyroscope on the X axis, denoted in units hertz (Hz).  

- **`timeBodyGyroStdY`** : `[double]` : Indicates average of the STD of time domain signals for body movement captured by gyroscope on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyGyroStdZ`** : `[double]` : Indicates average of the STD of time domain signals for body movement captured by gyroscope on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkMeanX`** : `[double]` : Indicates average of the MEAN of time domain signals for body 'Jerk' movement captured by gyroscope on the X axis, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkMeanY`** : `[double]` : Indicates average of the MEAN of time domain signals for body 'Jerk' movement captured by gyroscope on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkMeanZ`** : `[double]` : Indicates average of the MEAN of time domain signals for body 'Jerk' movement captured by gyroscope on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkStdX`** : `[double]` : Indicates average of the STD of time domain signals for body 'Jerk' movement captured by gyroscope on the X axis, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkStdY`** : `[double]` : Indicates average of the STD of time domain signals for body 'Jerk' movement captured by gyroscope on the Y axis, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkStdZ`** : `[double]` : Indicates average of the STD of time domain signals for body 'Jerk' movement captured by gyroscope on the Z axis, denoted in units hertz (Hz).  

- **`timeBodyAccMagMean`** : `[double]` :  Indicates average of the MEAN of magnitude of three-dimensional time domain signals for body movement captured by accelerometer, denoted in units hertz (Hz).  

- **`timeBodyAccMagStd`** : `[double]` :  Indicates average of the STD of magnitude of three-dimensional time domain signals for body movement captured by accelerometer, denoted in units hertz (Hz).  

- **`timeGravityAccMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional time domain signals for gravity movement captured by accelerometer, denoted in units hertz (Hz).  

- **`timeGravityAccMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional time domain signals for gravity movement captured by accelerometer, denoted in units hertz (Hz).  

- **`timeBodyAccJerkMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional time domain signals for body 'Jerk' movement captured by accelerometer, denoted in units hertz (Hz).  

- **`timeBodyAccJerkMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional time domain signals for body 'Jerk' movement captured by accelerometer, denoted in units hertz (Hz).  

- **`timeBodyGyroMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional time domain signals for body movement captured by gyroscope, denoted in units hertz (Hz).  

- **`timeBodyGyroMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional time domain signals for body movement captured by gyroscope, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional time domain signals for body 'Jerk' movement captured by gyroscope, denoted in units hertz (Hz).  

- **`timeBodyGyroJerkMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional time domain signals for body 'Jerk' movement captured by gyroscope, denoted in units hertz (Hz).  

- **`freqBodyAccMeanX`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`freqBodyAccMeanY`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`freqBodyAccMeanZ`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`freqBodyAccStdX`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`freqBodyAccStdY`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`freqBodyAccStdZ`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`freqBodyAccJerkMeanX`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body 'Jerk' movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`freqBodyAccJerkMeanY`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body 'Jerk' movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`freqBodyAccJerkMeanZ`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body 'Jerk' movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`freqBodyAccJerkStdX`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by accelerometer on the X axis, denoted in units hertz (Hz).  

- **`freqBodyAccJerkStdY`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by accelerometer on the Y axis, denoted in units hertz (Hz).  

- **`freqBodyAccJerkStdZ`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by accelerometer on the Z axis, denoted in units hertz (Hz).  

- **`freqBodyGyroMeanX`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body movement captured by gyroscope on the X axis, denoted in units hertz (Hz).  

- **`freqBodyGyroMeanY`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body movement captured by gyroscope on the Y axis, denoted in units hertz (Hz).  

- **`freqBodyGyroMeanZ`** : `[double]` : Indicates average of the MEAN of frequency domain signals for body movement captured by gyroscope on the Z axis, denoted in units hertz (Hz).  

- **`freqBodyGyroStdX`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by gyroscope on the X axis, denoted in units hertz (Hz).  

- **`freqBodyGyroStdY`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by gyroscope on the Y axis, denoted in units hertz (Hz).  

- **`freqBodyGyroStdZ`** : `[double]` : Indicates average of the STD of frequency domain signals for body movement captured by gyroscope on the Z axis, denoted in units hertz (Hz).  

- **`freqBodyAccMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional frequency domain signals for body movement captured by accelerometer, denoted in units hertz (Hz).  

- **`freqBodyAccMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional frequency domain signals for body movement captured by accelerometer, denoted in units hertz (Hz).  

- **`freqBodyAccJerkMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional frequency domain signals for body 'Jerk' movement captured by accelerometer, denoted in units hertz (Hz).  

- **`freqBodyAccJerkMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional frequency domain signals for body 'Jerk' movement captured by accelerometer, denoted in units hertz (Hz).  

- **`freqBodyGyroMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional frequency domain signals for body movement captured by gyroscope, denoted in units hertz (Hz).  

- **`freqBodyGyroMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional frequency domain signals for body movement captured by gyroscope, denoted in units hertz (Hz).  

- **`freqBodyGyroJerkMagMean`** : `[double]` : Indicates average of the MEAN of magnitude of three-dimensional frequency domain signals for body 'Jerk' movement captured by gyroscope, denoted in units hertz (Hz).  

- **`freqBodyGyroJerkMagStd`** : `[double]` : Indicates average of the STD of magnitude of three-dimensional frequency domain signals for body 'Jerk' movement captured by gyroscope, denoted in units hertz (Hz).  

-----

